### ISSUE TITLE
[FEATURE] Remember community folder location

### ISSUE THREAD

**Issue by adenflorian** [Externoak/A32NX-installer#1]
1. open installer
2. select community folder
3. close installer
4. open installer

Expected:
it should already have the community folder selected, based on the last time I opened the installer

Actual:
it makes me select my community folder again

**Comment by Externoak** [comment]
It should automatically detect your community folder. If it doesn't it should ask for it.

**Comment by Externoak** [comment]
Added check for special cases this should not happen anymore.
