### ISSUE TITLE
[BUG] Installer Keeps Saying "A32NX version is out of date, please consider updating"

### ISSUE THREAD

**Issue by speedbird5** [Externoak/A32NX-installer#15]
Mod Version

Development Version - "built": "2020-12-03T06:03:11+00:00"

Describe the bug

Installer Keeps Saying "A32NX version is out of date, please consider updating" even though have just updated using the installer.

To Reproduce

Run the installer once to update, then run it again and you will keep getting the "A32NX version is out of date, please consider updating" message.
Expected behavior

After updated, the installer should not keep saying update...

Actual behavior

As above

**Comment by Externoak** [comment]
Thanks for informing.

This is an error on the A32NX mod repository, the version has not been bumped correctly on that side. Nothing related to the installer, no further action is required on your side, hopefully the issue is resolved soon.
