### ISSUE TITLE
Request: Add option to download/update custom FBW dev version

### ISSUE THREAD

**Issue by sushiat** [Externoak/A32NX-installer#18]
Hi,

I'm using the custom fbw version with my tca quadrant and it works just beautiful with it and before switching to that I used your downloader to update the dev version all the time and loved the convenience. Could you add the custom fbw version as a third download option?

If I checked the url contained in the github readme for the project correctly **the tag for this version is "vmaster-cfbw".**

Cheers,
Markus

**Comment by Externoak** [comment]
Glad you enjoyed this little tool, I'm afraid I do not have the time at the moment to develop this tool further and also this installer will soon not be the standard installer and most likely archived when the new one comes out. [New installer repo](https://github.com/flybywiresim/installer) although I'm quite sure it will be announce when it is finally ready.

**Comment by sushiat** [comment]
Thx for getting back to me, didn't know about a new installer in the works. Even had a quick look at the code to see how quickly I could add this myself but turns out there isn't actually a release tag for that version currently. I will then wait patiently until the new one comes out. Thanks for the tool in any case, saved me loads of time in the past.
