### ISSUE TITLE
[SUGGESTION] Add console commands

### ISSUE THREAD

**Issue by alexx-ftw** [Externoak/A32NX-installer#7]
I think adding a couple of commands would greatly improve this software.

For example:
-dev -> would automatically compare with dev version and download if necessary.
-stable -> same as above but with stable version.
-silent -> do above tasks and close app
-opensim -> open the sim when finished.

Maybe some more would be useful also but I can't think of any more right now.
Just my .02!

**Comment by Externoak** [comment]
Thanks for the feedback,

For the time being I do not plan on adding console commands since this software is intended to be used as a GUI. If more people express desire of a feature like this I will consider adding this feature in the future.
