### ISSUE TITLE
Suggested improvement : destination folder

### ISSUE THREAD

**Issue by johnwillimas** [Externoak/A32NX-installer#8]
Currently the installer defaults to the MSFS Community folder and displays that on start up. If you select an alternate folder using "Change Destination Folder" it would be helpful to have the app remember this so that it does not have to be changed each time the program is run. (I currently use an add-on switching app - [https://flightsim.to/file/1572/msfs-addons-linker] - to manage my addons and so I use a staging folder outside of MSFS to hold the addons, including the A32NX.)

**Comment by Externoak** [comment]
Thanks for the feedback, I initially created it to only detect for the Community folder by default. 

I will see if I can add a feature in the next release to remember the lasted used folder.

**Comment by Externoak** [comment]
Feature will be available in version v0.7 onwards.
