### ISSUE TITLE
Very slow download

### ISSUE THREAD

**Issue by daniloraisi** [Externoak/A32NX-installer#9]
I'm using FlyByWire Downloader since the beginning, and it's a great tool! Congratulations!

Since the last 3 attempts to download the Development Version of A320NX, I'm facing slow download speed!

I'm a developer, and I use Git daily, without any problems, but when using the Downloader, the speed is slow, as you can see in the image:

![image](https://user-images.githubusercontent.com/38328735/98706576-c0e38900-235d-11eb-87c8-36490911ab9d.png)

**Comment by Externoak** [comment]
Thanks for the feedback.

It seems like some users experience some kind of download throttle from GitHub API. 

See https://github.com/Externoak/A32NX-installer#faqs.
Quote:
Q: Why is my download speed so slow?

A: Your download speed from GitHub may vary depending on your connection to their servers, the Downloader will always use all available bandwidth.

I'm afraid it is not something I can reproduce, just a handful of users who experience this with no concrete pattern.

We are working on a solution to avoid this problem by using our own CDN servers to ensure maximal download speed. I do not currently have an ETA on when this will be available but I will close this issue when this is the case.

**Comment by Externoak** [comment]
Feature will be available in version v0.7 onwards. It is possible to choose the download server now (Github, FlyByWire CDN, or non CDN)
